---
- name: setup nosql storage
  tags: tsuru_nosql
  include_role:
    name: stone-payments.mongodb
  vars:
    mongodb_conf_bindIp: "0.0.0.0"
    mongodb_conf_port: "{{ tsuru_portNoSQL }}"
    mongodb_conf_auth: true
    mongodb_conf_key: "{{ tsuru_replKey }}"
    mongodb_replSet_enabled: true
    mongodb_replSet_name: "{{ tsuru_nameRs }}"
    mongodb_replSet_master: "{{ tsuru_addrMaster }}"
    mongodb_replSet_isMaster: "{{ isMaster }}"
    mongodb_admin_password: "{{ tsuru_passAdmin }}"
  when: tsuru_nosql

- name: setup inmemory storage
  tags: tsuru_inmem
  include_role:
    name: stone-payments.redis
  vars:
    redis_srv_conn_bind: "0.0.0.0"
    redis_srv_conn_port: "{{ tsuru_portInMem }}"
    redis_srv_sec_password: "{{ tsuru_passAdmin }}"
    redis_srv_repl_isMaster: "{{ isMaster }}"
    redis_srv_repl_slavePriority: "{{ 1 if isMaster else 100 }}"
    redis_srv_repl_masterAddr: "{{ tsuru_addrMaster }} {{ tsuru_portInMem }}"
    redis_sent_enabled: true
    redis_sent_monitors:
      - name: "{{ tsuru_nameMaster }}"
        host: "{{ tsuru_addrMaster }}"
        port: "{{ tsuru_portInMem }}"
        quorum: 2
        auth_pass: "{{ tsuru_passAdmin }}"
        down_after_milliseconds: 3000
  when: tsuru_inmem

- name: setup search storage
  tags: tsuru_search
  include_role:
    name: stone-payments.elasticsearch
  vars:
    es_instance_name: "{{ ansible_hostname }}"
    es_config:
        cluster.name: "{{ tsuru_nameRs }}"
        discovery.zen.ping.unicast.hosts: "{{ tsuru_addrMaster }} {{ tsuru_portSearchTransport }}"
        network.host: "0.0.0.0"
        http.port: "{{ tsuru_portSearch }}"
        transport.tcp.port: "{{ tsuru_portSearchTransport }}"
        node.data: true
        node.master: "{{ isMaster }}"
        bootstrap.memory_lock: false
    es_heap_size: "1g"
    es_scripts: false
    es_templates: false
    es_version_lock: true
    es_plugins:
     - plugin: ingest-geoip
  when: tsuru_search
